# Generated by Django 5.0.3 on 2024-03-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Help others by donating to their fundraiser, or start one for someone you care about.'),
        ),
    ]
