# Generated by Django 5.0.3 on 2024-03-06 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundprojects.project'),
        ),
    ]
