# Generated by Django 5.0.3 on 2024-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0009_project_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateField(),
        ),
    ]
