# Generated by Django 5.0.3 on 2024-03-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0011_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('done', 'Done')], default='active', max_length=10),
        ),
    ]
