# Generated by Django 5.0.3 on 2024-03-09 19:39

import django.db.models.deletion
import fundprojects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0012_alter_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='commentsreports',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='projectsreports',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=fundprojects.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentsreports',
            name='user',
            field=models.ForeignKey(default=fundprojects.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(default=fundprojects.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=fundprojects.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsreports',
            name='user',
            field=models.ForeignKey(default=fundprojects.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=fundprojects.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
