# Generated by Django 5.0.3 on 2024-03-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0017_featuredprojects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredprojects',
            name='created_at',
        ),
    ]
