# Generated by Django 5.0.3 on 2024-03-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundprojects', '0018_remove_featuredprojects_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FeaturedProjects',
        ),
    ]
