# Generated by Django 5.0.3 on 2024-03-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autun', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='profile_img',
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
